window.GENENV_CONTENT = {
  source: {
    type: "notion-snapshot",
    pageTitle: "GenEnv Lab",
    pageUrl: "https://www.notion.so/36dd18514cb2803cbd6dfa95d96a942b",
    databaseTitle: "GenEnv Website Content",
    databaseUrl: "https://www.notion.so/553e135d31ef489497c2faeb9a6eb043",
    dataSourceUrl: "collection://e8374bc0-afb0-4f05-8f50-f70a39284acc",
    updated: "2026-05-27",
  },
  projects: [
    {
      title: "Design as Language",
      year: "2026",
      type: "Workshop / Research",
      status: "current",
      description: "A DigitalFUTURES workshop developing design language, AI agents, and computational modeling workflows.",
      tags: ["research", "course", "AI", "design"],
      palette: ["#07111a", "#6cb7ff", "#0d2c3d", "#eff8ff"],
      texture: "grid",
      href: "pages/design-as-language.html",
    },
    {
      title: "Grasshopper MCP",
      year: "2026",
      type: "Tool",
      status: "current",
      description: "An evolving tool that connects LLM agents to Grasshopper through MCP, tool calls, skills, and multiple modes of interaction.",
      tags: ["research", "tool", "AI", "computation"],
      palette: ["#06140f", "#35f4c7", "#15392d", "#eff8ff"],
      texture: "mesh",
      href: "pages/grasshopper-mcp.html",
    },
    {
      title: "Computational Lexicalization",
      year: "2026",
      type: "Writing",
      status: "in press",
      description: "A theoretical article for Architectural Journal on design agents, computational design, and language-based modeling.",
      tags: ["publication", "writing", "AI", "theory"],
      palette: ["#130d1f", "#c994ff", "#2a183e", "#eff8ff"],
      texture: "scan",
      href: "pages/computational-lexicalization.html",
    },
    {
      title: "Landscape Agent",
      year: "2025",
      type: "Workshop / Research",
      status: "published",
      description: "A DigitalFUTURES workshop and research project testing landform modeling tasks with AI agents; published in the NeurIPS Creative AI track.",
      tags: ["research", "course", "AI", "landscape"],
      palette: ["#07111a", "#6cb7ff", "#17283b", "#eff8ff"],
      texture: "mesh",
      href: "pages/landscape-agents.html",
    },
    {
      title: "Code2Code",
      year: "2019-2026",
      type: "Research",
      status: "current",
      description: "A line of work beginning with NYC Department of City Planning and moving toward transparent urban form visualization, AI agents, and RAG workflows.",
      tags: ["research", "urbanism", "tool", "AI"],
      palette: ["#07111a", "#6cb7ff", "#182c45", "#eff8ff"],
      texture: "grid",
      href: "pages/code2code.html",
    },
    {
      title: "AI4DM",
      year: "2026",
      type: "Teaching / Research",
      status: "current",
      description: "Research on how AI reshapes design media education, tool learning, representation, and architectural / landscape architectural curricula.",
      tags: ["research", "course", "AI", "media"],
      palette: ["#1b1010", "#ff6f61", "#3c1e1e", "#eff8ff"],
      texture: "contour",
      href: "pages/ai4dm.html",
    },
    {
      title: "Open Positions + Collaborations",
      year: "2026",
      type: "Opportunity",
      status: "open",
      description: "Prospective PhD students, UBC research assistants, and external collaborators are invited to contact the lab with focused proposals and relevant work samples.",
      tags: ["people", "collaboration", "phd", "RA"],
      palette: ["#171713", "#f5df7a", "#3b3420", "#eff8ff"],
      texture: "grid",
      href: "pages/open-positions.html",
    },
  ],
  nodes: [
    {
      id: "design-language",
      label: "Design Language",
      title: "Design as Language",
      meta: "Research / Workshop · 2026",
      description: "DigitalFUTURES workshop exploring design language, AI agents, and computational modeling workflows.",
      type: "research",
      tags: ["AI", "design", "workshop"],
      gx: 7,
      gy: 7,
      href: "pages/design-as-language.html",
    },
    {
      id: "grasshopper-mcp",
      label: "GH MCP",
      title: "Grasshopper MCP",
      meta: "Tool · 2026",
      description: "LLM-to-Grasshopper tool infrastructure using MCP, skills, and agentic tool calls.",
      type: "tool",
      tags: ["AI", "tool", "computation"],
      gx: 14,
      gy: 6,
      href: "pages/grasshopper-mcp.html",
    },
    {
      id: "comp-lex",
      label: "Lexicalization",
      title: "Computational Lexicalization",
      meta: "Writing · 2026",
      description: "The theoretical writing connected to agentic computational design and Grasshopper MCP.",
      type: "writing",
      tags: ["writing", "theory", "AI"],
      gx: 10,
      gy: 13,
      href: "pages/computational-lexicalization.html",
    },
    {
      id: "landscape-agent",
      label: "Landscape Agent",
      title: "Landscape Agent",
      meta: "Research / Workshop · 2025",
      description: "Agent-based landform modeling workshop and research project linked to Grasshopper MCP.",
      type: "research",
      tags: ["landscape", "AI", "workshop"],
      gx: 17,
      gy: 13,
      href: "pages/landscape-agents.html",
    },
    {
      id: "code2code",
      label: "Code2Code",
      title: "Code2Code",
      meta: "Research · 2019-2026",
      description: "Urban form visualization, AI agents, and transparent RAG workflows emerging from professional computational planning work.",
      type: "research",
      tags: ["urbanism", "AI", "visualization"],
      gx: 6,
      gy: 18,
      href: "pages/code2code.html",
    },
    {
      id: "ai4dm",
      label: "AI4DM",
      title: "AI4DM",
      meta: "Teaching / Research · 2026",
      description: "AI in design media curriculum, representation, and tool learning.",
      type: "teaching",
      tags: ["AI", "media", "teaching"],
      gx: 25,
      gy: 8,
      href: "pages/ai4dm.html",
    },
    {
      id: "open-positions",
      label: "Open Positions",
      title: "Open Positions + Collaborations",
      meta: "People · Open",
      description: "Opportunities for PhD students, research assistants, and external collaborators.",
      type: "people",
      tags: ["phd", "RA", "collaboration"],
      gx: 27,
      gy: 18,
      href: "pages/open-positions.html",
    },
  ],
  edges: [
    ["design-language", "grasshopper-mcp"],
    ["design-language", "landscape-agent"],
    ["grasshopper-mcp", "comp-lex"],
    ["grasshopper-mcp", "landscape-agent"],
    ["comp-lex", "code2code"],
    ["landscape-agent", "code2code"],
    ["ai4dm", "design-language"],
    ["ai4dm", "landscape-agent"],
    ["open-positions", "design-language"],
    ["open-positions", "grasshopper-mcp"],
    ["open-positions", "ai4dm"],
  ],
};
